### PR TITLE
Drops `openssl` pin

### LINKED ISSUE #9: Unpin `openssl`
Currently `openssl` is pinned in the recipe. Would be good to unpin this so  `openssl` 3 can be used

https://github.com/conda-forge/kubo-feedstock/blob/81ad90eb5a09f1ff71f795f5875d456b7627fcbc/recipe/conda_build_config.yaml#L8-L9

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #9.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes https://github.com/conda-forge/kubo-feedstock/issues/9

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by bollwyvl** [comment]
Perhaps the bot will have to come back along, or otherwise be manually migrated?

**Comment by h-vetinari** [comment]
> Perhaps the bot will have to come back along, or otherwise be manually migrated?

This feedstock already [contains](https://github.com/conda-forge/kubo-feedstock/blob/main/.ci_support/migrations/openssl3.yaml) the openssl 3 migrator. :)

**Comment by jakirkham** [comment]
Given the migrator was added in PR ( https://github.com/conda-forge/kubo-feedstock/pull/3 ) and the original bot PR ( https://github.com/conda-forge/kubo-feedstock/pull/1 ) was closed, am guessing the bot won't come by.

Was a little surprised re-rendering didn't have an effect, but then again the CI matrix already included both `openssl` versions.

Edit: Sorry for the duplicative post. GitHub didn't show the new comment

**Comment by bollwyvl** [comment]
Welp, fewer pins good. Let's merge and see what happens.

**Pull request merged**
